// section3_lx/w5_React/src/components/todolist/TodoContent.jsx
import React from "react";
import TodoItem from "./TodoItem";
import List from "../List";
import Button from "../Button";
import context from "./context";
function TodoContent({ datalist}) {
    const { remove, complete} = React.useContext(context)
    
    const column=[
        // {
        //     label:<input type="checkbox" />,
        //     render(row,idx){
        //         return <input type="checkbox" onChange={checked} onClick={seleIds(row.id)}/>
        //     }
        // },
        {
            label:'#',
            render(row,idx){
                return idx+1
            }
        },
        {
            label:'代办事项',
            dataKey:'todo'
        },
        {
            label:'是否完成',
            dataKey:'done',
            render(row){
                return row.done?'是':'否'
            }
        },
        {
            label:'操作',
            render(row){
                return(
                    <>
                        <Button className="btn-primary" onClick={complete.bind(null,row.id)}>{row.done===true?'取消':'完成'}</Button>
                        <Button className="btn-danger" onClick={remove.bind(null,row.id)}>删除</Button>
                    </>
                )
            }
        },
      ]
    return (
        <div className="TodoContent">
           {/* { <table className="table table-striped ">
                <thead>
                    <tr>
                        <th scope="col"><input type="checkbox" 
                        /></th>
                        <th scope="col">#</th>
                        <th scope="col">待办事项</th>
                        <th scope="col">是否完成</th>
                        <th scope="col">时间</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                    {
                        datalist.map((item, idx) => {
                            return <TodoItem key={item.id} item={item} index={idx} />
                        })
                    }

                </tbody>
            </table>} */}
            <List rowKey="id" datasource={datalist} column={column}>

            </List>
        </div>
    )
}

export default TodoContent

// section3_lx/w3_VueCLI/app/src/components/TodoList/TodoContent.vue
<template>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"><input type="checkbox" v-model="checkAll" /></th>
          <th scope="col">#</th>
          <th scope="col">代办事项</th>
          <th scope="col">添加时间</th>
          <th scope="col">是否完成</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
    <tbody>
      <TodoItem v-for="(item,idx) in list" :key="item.id" :item="item" :idx="idx"></TodoItem>
    </tbody>
    </table>
</template>

<script>
import TodoItem from './TodoItem.vue'
export default {
  name: "TodoContent",
  props: ["list"],
  inject: ["selectIds", "selectAll"],
  computed: {
    checkAll: {
      get() {
        return this.list.every((item) => this.selectIds.includes(item.id));
      },
      set(newValue) {
        // this.selectAll(newValue)
        this.$parent.selectIds.splice(0, this.$parent);
        if (newValue) {
          const ids = this.list.map((item) => item.id);
          this.$parent.selectIds.push(...ids);
        }
      },
    },
  },

  components: {
    TodoItem,
  },
};
</script>
<style>
</style>
