// section3_lx/w6_ReactRouter/src/views/Login.jsx
import React from "react";
import request from '../utils/request'
import {Form,Input,Checkbox,Button,message} from 'antd'
function Login(props) {
    const onFinish=function(values){
        console.log('values',values);

        request.get('/user/login',{
            params:values
        }).then(({data})=>{
            if(data.status===200){
                localStorage.setItem('userInfo',JSON.stringify(data.data));
                props.history.push('/manage')
                message.success('登录成功')
            }else{
                message.error('用户名或密码错误')
            }
        })
    }
    return (
        <div className="login-from">
            <h1>面试题后台管理系统</h1>
            <Form
                name="basic"
                labelCol={{ span: 8 }}
                wrapperCol={{ span: 12 }}
                initialValues={{ remember: true }}
                onFinish={onFinish}
                autoComplete="off"
            >
                <Form.Item
                    label="用户名"
                    name="username"
                    rules={[{ required: true, message: '请输入用户名' }]}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label="密码"
                    name="password"
                    rules={[{ required: true, message: '请输入密码' }]}
                >
                    <Input.Password />
                </Form.Item>

                <Form.Item name="remember" valuePropName="checked" wrapperCol={{ offset: 8, span: 12 }}>
                    <Checkbox>下次免登录</Checkbox>
                </Form.Item>

                <Form.Item wrapperCol={{ offset: 8, span: 12 }}>
                    <Button type="primary" htmlType="submit">
                        登录
                    </Button>
                </Form.Item>
            </Form>
        </div>
    )
}

export default Login;

// section3_lx/w3_VueRouter/app/src/views/Login.vue
<template>
  <div>
    <h1>用户登录</h1>
    <van-form @submit="onSubmit">
      <van-field
        v-model="username"
        name="username"
        label="用户名"
        :rules="[{ required: true, message: '请填写用户名' }]"
      />
      <van-field
        v-model="password"
        type="password"
        name="password"
        label="密码"
        :rules="[{ required: true, message: '请填写密码' }]"
      />
      <div style="margin: 16px">
        <van-button round block type="info" native-type="submit"
          >登录</van-button
        >
        <span>还没有账号?点击去<a @click="goto('/reg')">注册</a></span>
      </div>
    </van-form>
  </div>
</template>
<script>
export default {
  name: "Login",
  data() {
    return {
      username: "",
      password: "",
    };
  },
  created() {
    console.log("Login", this);
  },
  methods: {
    onSubmit(value) {
      //value:必须给表单元素添加name属性才能获取值
      // console.log("value", value);
      this.$request.post("/login", value).then(({ data }) => {
        // console.log("data=", data);
        localStorage.setItem("userInfo", JSON.stringify(data.data));
        
        this.$toast("登录成功");
        const { targetUrl = "/mine" } = this.$route.query;
        this.$router.replace(targetUrl);
      });
    },
    goto(value) {
      this.$router.push(value);
    },
  },
};
</script>
<style >
a {
  color: #58bc58;
}
</style>
