// section3_lx/w3_VueCLI/app/src/components/TodoList/TodoList.vue
<template>
  <div class="container">
    <todo-form :add="addItem" v-on:additem="addItem" ref="todoForm"></todo-form>
    <todo-control
      :completeItems="completeItems"
      :removeItems="removeItems"
    ></todo-control>
    <todo-content :list="datalist"></todo-content>
    <todo-footer v-slot="{ donelist, undonelist }" :list="datalist">
      <p><strong>total:</strong>{{ datalist.length }}</p>
      <p>complete:{{ donelist.length }}</p>
      <p>uncomplate:{{ undonelist.length }}</p>
    </todo-footer>
  </div>
</template>

<script>
import TodoForm from "./TodoForm.vue";
import TodoControl from "./TodoControl.vue";
import TodoContent from "./TodoContent.vue";
import TodoFooter from "./TodoFooter.vue";
//引入样式
import "bootstrap/dist/css/bootstrap.css";

//Bus方法
// 方法一：引入Vue文件创建Bus并导出
// import Vue from 'vue';
// export const Bus=new Vue()
//方法二：引入Bus.js链接todoitem（推荐使用）
import Bus from './Bus'

export default {
  name: "TodoList",
  data() {
    //给Bus添加事件 ，并把todoList的方法作为事件处理函数
    Bus.$on("removeItem", this.removeItem);
    Bus.$on("completeItem", this.completeItem);
    return {
      selectIds: [],
      datalist: [
        {
          id: 1,
          todo: "定个小目标，全球旅行",
          done: true,
          addtime: Date.now(),
        },
        {
          id: 2,
          todo: "赚他一个亿津巴布韦币",
          done: false,
          addtime: Date.now() + 3600 * 1000,
        },
        {
          id: 3,
          todo: "迎娶白富美，达到人生巅峰",
          done: false,
          addtime: Date.now() + 3600 * 1000 * 5,
        },
      ],
    };
  },
  //依赖注入
  provide: function () {
    return {
      selectItem: this.selectItem,
      selectIds: this.selectIds,
      selectAll: this.selectAll,
      // completeItem: this.completeItem,
      // removeItem: this.removeItem,
    };
  },
  components: {
    TodoForm,
    TodoControl,
    TodoContent,
    TodoFooter,
  },
  methods: {
    //添加
    addItem(todo) {
      if(!(todo == "" || todo == undefined || todo == null || (todo.length>0 && todo.trim().length == 0))){
        const newData = {
          id: parseInt(Math.random() * 10000),
          //需要输入框中的内容
          todo,
          done: false,
          addtime: Date.now(),
        };
        this.datalist.unshift(newData);
      }
    },
    //完成
    completeItem(id) {
      this.datalist.forEach((item) => {
        if (item.id === id) {
          item.done = !item.done;
        }
      });
    },
    //删除
    removeItem(id, e) {
      this.datalist = this.datalist.filter((item) => item.id != id);
    },
    //单选
    selectItem(id) {
      if (!this.selectIds.includes(id)) {
        this.selectIds.push(id);
      } else {
        // this.selectIds = this.selectIds.filter(item => item != id)
        const idx = this.selectIds.findIndex((item) => item === id);
        this.selectIds.splice(idx, 1);
      }
    },
    //全选
    selectAll(all) {
      if (all) {
        //由于是通过provide/inject传入的值所有以下写法达不到响应式结果
        // this.selectIds=this.datalist.map(item=>item.id)
        const ids = this.datalist.map((item) => item.id);
        this.selectIds.splice(0, this.selectIds.length);
        this.selectIds.push(...ids);
      } else {
        this.selectIds.splice(0, this.selectIds.length);
      }
    },
    //批量完成
    completeItems() {
      this.datalist.forEach((item) => {
        if (this.selectIds.includes(item.id)) {
          item.done = true;
        }
      });
    },
    //批量删除
    removeItems() {
      this.datalist = this.datalist.filter((item) => {
        return !this.selectIds.includes(item.id);
      });
    },
  },
};
</script>
<style>
</style>

// section3_lx/w5_React/src/components/todolist/Todolist.jsx
import React,{PureComponent} from "react"
import TodoFrom from './TodoFrom'
import TodoContent from './TodoContent'
import TodoFoot from './TodoFoot'

import context from "./context"
import 'bootstrap/dist/css/bootstrap.css'
class Todolist extends PureComponent {
    // constructor() {
    //     super()
    //     //定义组件状态（数据）
    //     this.state = {
    //         // count:1,
    //         datalist: [
    //             {
    //                 id: 1,
    //                 todo: '定个小目标，赚它一个亿',
    //                 done: true,
    //                 addtime: Date.now() + 100
    //             },
    //             {
    //                 id: 2,
    //                 todo: '一天睡两年',
    //                 done: false,
    //                 addtime: Date.now() + 100
    //             },
    //             {
    //                 id: 3,
    //                 todo: '达成秒睡',
    //                 done: false,
    //                 addtime: Date.now() + 100
    //             },
    //         ]
    //     }
    //     // this.addItem = this.addItem.bind(this)
    //     // this.completeItem = this.completeItem.bind(this)
    //     // this.removeItem = this.removeItem.bind(this);
    // }
    state = {
        // count:1,
        selectIds:[],
        checked:false,
        datalist: [
            {
                id: 1,
                todo: '定个小目标，赚它一个亿',
                done: true,
                addtime: Date.now() + 100
            },
            {
                id: 2,
                todo: '一天睡两年',
                done: false,
                addtime: Date.now() + 100
            },
            {
                id: 3,
                todo: '达成秒睡',
                done: false,
                addtime: Date.now() + 100
            },
        ]
    }
    //在这里定义的方法会成为原型方法
    addItem=(todo)=> {
        const newItem = {
            id: parseInt(Math.random() * 10000),
            todo,
            done: false,
            addtime: Date.now()
        }
        //react 中不能直接修改原来的状态，而是使用一个新的值去覆盖
        const datalist = [...this.state.datalist]
        datalist.unshift(newItem)
        this.setState({
            datalist
        })
    }
    //定义时使用箭头函数
    completeItem=(id)=> {
        const { datalist } = this.state
        const newDatalist = datalist.map(item => {
            if (item.id === id) {
                item.done = !item.done
            }
            return { ...item }
        })
        this.setState({
            datalist: newDatalist
        })
    }
    removeItem=(id)=>  {
            // [{},{},{}] -> [{},{}]
            const newDatlist = this.state.datalist.filter(item=>item.id!==id).map(item=>({...item}))
        this.setState({
            datalist:newDatlist
        })
        console.log('newDatlist',newDatlist);
    }
    selectItem=(id)=> {
        const sleId=this.state.selectIds
        if(!sleId.includes(id)){
            sleId.push(id)
            this.setState({
                selectIds:sleId
            })
        }else{
            const idx=sleId.findIndex(item=>item===id)
            sleId.splice(idx,1)
        }
        console.log('selectIds',sleId);
    }
    render() {
        //在类组件中
        // console.log('todolist.render', this);
        const { datalist } = this.state
        return (
            <context.Provider value={{add:this.addItem, remove: this.removeItem, complete: this.completeItem,seleIds:this.selectItem}}>
                <div className="TodoList">
                    <TodoFrom  />
                    <TodoContent datalist={datalist} />
                    <TodoFoot datalist={datalist} />
                </div>
            </context.Provider>
        )
    }

}

export default Todolist;
