// section3_lx/w3_VueCLI/app/src/components/TodoList/TodoItem.vue
<template>
  <tr @click="selectItem(item.id)">
    <td><input type="checkbox" :checked="selectIds.includes(item.id)" /></td>
    <th scope="row">{{ idx + 1 }}</th>
    <td>{{ item.todo }}</td>
    <td v-once>{{ formatDate(item.addtime) }}</td>
    <!-- <td v-once>{{formatDate(item.addtime)}}</td> -->
    <td>{{ item.done ? "是" : "否" }}</td>
    <td>
      <button
        type="button"
        class="btn btn-outline-success btn-sm"
        @click.stop="completeItem(item.id)"
      >
        {{ item.done ? "取消" : "完成" }}
      </button>
      <button
        type="button"
        class="btn btn-outline-danger btn-sm"
        @click.stop="removeItem(item.id)"
      >
        删除
      </button>
    </td>
  </tr>
</template>

<script>
// 对应TodoList方法一：引入TodoList.vue文件中的Bus
// import {Bus} from './TodoList.vue'

// 对应TodoList方法二：引入Bus.js文件链接TodoList的bus （推荐）
import Bus from './Bus'

export default {
  name: "TodoItem",
  props: ["item", "idx"],
  inject: ["selectItem", "selectIds"],
  computed: {
    date() {
      console.log("date");
      return new Date(this.item.addtime).toLocaleDateString();
    },
  },
  methods: {
    completeItem(id) {
      Bus.$emit("completeItem", id);
    },
    removeItem(id) {
      Bus.$emit("removeItem", id);
    },
    formatDate(d) {
      console.log("formatDate");
      return new Date(d).toLocaleDateString();
    },
  },
};
</script>
<style>
</style>

// section3_lx/w5_React/src/components/todolist/TodoItem.jsx
import React from "react";
import context from "./context";
import Button from "../Button";
function TodoItem({ item, index }) {
    const { remove, complete } = React.useContext(context)
    return (

        <tr >
            <td><input type="checkbox" /></td>
            <td scope="row">{index + 1}</td>
            <td>{item.todo}</td>
            <td>{item.done ? <button className="btn btn-outline-secondary" disabled>是</button> : <button className="btn btn-outline-secondary" disabled >否</button>}</td>
            <td>{item.addtime}</td>
            <td>
                {/* {<button type="button" className="btn btn-primary" onClick={complete.bind(null, item.id)}>{item.done ? '取消' : '完成'}</button>
                <button type="button" className="btn btn-danger" onClick={remove.bind(null, item.id)}>删除</button> */}
                <Button className="btn-primary" onClick={complete.bind(null, item.id)}>{item.done ? '取消' : '完成'}</Button>
                <Button className="btn-danger" onClick={remove.bind(null,item.id)}>删除</Button>
            </td>
        </tr>
    )
}

export default TodoItem
